### ISSUE TITLE
Securing the webhooks

### ISSUE THREAD

**Issue by jaquesp** [benzman81/homebridge-http-webhooks#10]
Is there any way we can add user/pass auth to the webhooks?
Concerned that anyone with the correct URL could control my house!

Thanks,
Paul

**Comment by benzman81** [comment]
Not yet, but feel free to contribute.

**Comment by paolotremadio** [comment]
Hi @jaquesp. My pull request has just been merged. You can now set an optional username/password to add HTTP basic authentication to the web hooks.

More details on the README

**Comment by benzman81** [comment]
solve, thanks to @paolotremadio #25
