### ISSUE TITLE
Plugin name typo in Config UI X

### ISSUE THREAD

**Issue by jsiegenthaler** [benzman81/homebridge-http-webhooks#100]
I saw this yesterday:

The Plugin name in Config UI X is missing the h. It shows as Webooks, not Webhooks

Homebridge **Webooks**

To confirm it was nothing to do with my setup, I uninstalled and reinstalled the plugin.
No change, the typo was still there.
Observed in homebridge-http-webhooks v0.1.3

**Comment by monza258** [comment]
Thanks for the hint.

@jsiegenthaler Bezüglich ffmpeg:
(monza258(at)web.de)

**Comment by benzman81** [comment]
Next release will include the fix .
