### ISSUE TITLE
Darstellung Temperatur Sensor in Homebridge

### ISSUE THREAD

**Issue by jonaspies** [benzman81/homebridge-http-webhooks#104]
Hallo, seit iOS 14 wird die Temperatur des D1 Minis nur noch oben in der Leiste angezeigt, das wäre noch nichtmal so das Problem, allerdings habe ich einen innen und einen außen, die Temperatur wird dann oben zusammengefasst, anstatt das jeder Sensor einzeln angegeben wird, wenn man auf die Temperatur drückt, stehen auch wieder beide da, aber das ist etwas blöd, deshalb wollte ich fragen ob man das ändern kann.

Vielen Dank!

Hello, since iOS 14 the temperature of the D1 Mini is only displayed at the top in the bar, that wouldn't even be the problem, but I have one inside and one outside, the temperature is then summarized above instead of each sensor being specified individually  If you press the temperature, they both stand there again, but that's a bit stupid, so I wanted to ask if you can change that.

 Thank you so much!

![93FC19D6-9BBB-466D-ADCB-A04AE240FAE7](https://user-images.githubusercontent.com/61885505/93723399-974c8380-fb9e-11ea-93e6-208567ecc3c2.jpeg)
![0611770D-F5E0-4293-9342-7FF690044E8D](https://user-images.githubusercontent.com/61885505/93723402-9b78a100-fb9e-11ea-8641-ad4eab48756c.jpeg)

**Comment by benzman81** [comment]
This is the new layout of iOS14, there is nothing possible on my side to change this. I think you problem is, that you should define a new room "balcony/terrace" and put the "outside" sensor in this one.

**Comment by jonaspies** [comment]
Okay thank you
