### ISSUE TITLE
Waits for a response to close the roller shutter

### ISSUE THREAD

**Issue by jujuliveplay** [benzman81/homebridge-http-webhooks#105]
Hello

I would like to use your plugin for roller shutters that I order with a webhook.

its working fine except when closing where it waits for a response.

how do you keep them from waiting for an answer?

Thank you

**Comment by benzman81** [comment]
duplicateof #62

**Comment by benzman81** [comment]
fixed in 0.1.7

**Comment by benzman81** [comment]
this happens as HomeKit wanted to get a feedback from the roller shutter of current position using web hooks. I guess you did not use it this way. Thats why I added a new option "auto_set_current_position". Set it to true and it doesn't wait for feedback. Since version 0.1.7.
