### ISSUE TITLE
AccessoryId did not return a response body from 'changeFromServer' error

### ISSUE THREAD

**Issue by genfersee** [benzman81/homebridge-http-webhooks#107]
Dear all,

For a few weeks now, I get the following error in Homebridge logs when I call the following URL on a button:
get://192.168.xx.xx:yyyy/?accessoryId=mystromstatelessswitch&buttonName=Appart&event=0

[ERROR Http WebHook Server] AccessoryId 'mystromstatelessswitch' did not return a response body from 'changeFromServer'.

This however works as expected: my light gets ON!

My config is as follow:
            "platform": "HttpWebHooks",
            "webhook_port": "yyyy",
            "cache_directory": "/home/pi/.homebridge/node-persist/storage",
            "statelessswitches": [
                {
                    "id": "mystromstatelessswitch",
                    "name": "Boutons",
                    "buttons": [
                        {
                            "name": "Appart"
                        }
                    ]
                }

Am I doing something incorrect?
Many thanks in advance!

**Comment by benzman81** [comment]
Stateless switch web hook did not return a response. This is now fixed in 0.1.8.

**Comment by genfersee** [comment]
Many thanks! I will test again when home!

**Comment by genfersee** [comment]
I confirm bug is fixed, many thanks!
