### ISSUE TITLE
Switch with self signed Certificate

### ISSUE THREAD

**Issue by monza258** [benzman81/homebridge-http-webhooks#111]
Hallo Benzman,

wenn ich einen Switch habe mit dem ich einen Webhook auslösen möchte, bekomme ich einen Fehler bzgl. Error: self signed certificate. Es handelt sich dabei um einen https link. Das Zertifikat ist von mir vorhanden. Gibt es da eine Lösung? Eventuell einen Ordner der auf das Zertifikat zugreift wenn der Befehl ausgeführt wird?

Englisch bin ich nicht gang so fit. Deshalb in Deutsch. Verstehst du ja;-) 

```

17:26:52] [HttpWebHooks] Request to 'https://webhook.de:3333' finished with status code '-1' and body 'undefined'. Error: self signed certificate
Dec 02 17:26:52 raspberrypi4 homebridge[11400]:     at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
Dec 02 17:26:52 raspberrypi4 homebridge[11400]:     at TLSSocket.emit (events.js:315:20)
Dec 02 17:26:52 raspberrypi4 homebridge[11400]:     at TLSSocket._finishInit (_tls_wrap.js:932:8)
Dec 02 17:26:52 raspberrypi4 homebridge[11400]:     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
Dec 02 17:26:52 raspberrypi4 homebridge[11400]:   code: 'DEPTH_ZERO_SELF_SIGNED_CERT'

```

**Comment by monza258** [comment]
> Hallo Benzman,
> 
> wenn ich einen Switch habe mit dem ich einen Webhook auslösen möchte, bekomme ich einen Fehler bzgl. Error: self signed certificate. Es handelt sich dabei um einen https link. Das Zertifikat ist von mir vorhanden. Gibt es da eine Lösung? Eventuell einen Ordner der auf das Zertifikat zugreift wenn der Befehl ausgeführt wird?
> 
> Englisch bin ich nicht gang so fit. Deshalb in Deutsch. Verstehst du ja;-)
> 
> ```
> 
> 17:26:52] [HttpWebHooks] Request to 'https://webhook.de:3333' finished with status code '-1' and body 'undefined'. Error: self signed certificate
> Dec 02 17:26:52 raspberrypi4 homebridge[11400]:     at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
> Dec 02 17:26:52 raspberrypi4 homebridge[11400]:     at TLSSocket.emit (events.js:315:20)
> Dec 02 17:26:52 raspberrypi4 homebridge[11400]:     at TLSSocket._finishInit (_tls_wrap.js:932:8)
> Dec 02 17:26:52 raspberrypi4 homebridge[11400]:     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
> Dec 02 17:26:52 raspberrypi4 homebridge[11400]:   code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
> ```

EDIT: 
Sehe gerade du hast das bereits bedacht. Ich teste das mal.

```
"https_keyfile": "/pathToKeyFile/server.key", // (beta state, optional, only if you like to secure your api using ssl certificate)
"https_certfile": "/pathToKeyFile/server.cert", // (beta state, optional, only if you like to secure your api using ssl certificate)
                
```

**Comment by benzman81** [comment]
@monza258 ne, diese einstellung ist dafür, wenn man den webhook server per ssl mit einem eigenen key absichern möchte.

**Comment by monza258** [comment]
> @monza258 ne, diese einstellung ist dafür, wenn man den webhook server per ssl mit einem eigenen key absichern möchte.

Ohh ok, kannst du eine Option dafür einbauen das ich für eine Anfrage ein eigenes Zertikat nutzen kann?

**Comment by benzman81** [comment]
Now supported in 0.1.10.
