### ISSUE TITLE
Cannot have 2 x switches with same name

### ISSUE THREAD

**Issue by jsiegenthaler** [benzman81/homebridge-http-webhooks#119]
I wanted 2 x switches with the same name, but in different rooms

Webhooks lets me save the config but the UUID for both accessories is then the same, and this causes a homebridge conflict

Can the uuid be build from id & name, instead of just name? That would solve the issue...

Looks like the uuid is set here:

` this.service = new Service.Switch(this.name);`

If the uuid is an arbitary value, then changing this line to

` this.service = new Service.Switch(this.id + this.name);`

would solve the issue

**Comment by benzman81** [comment]
Just use different names in the config and rename the device in the Home App.
