### ISSUE TITLE
Support For Speaker

### ISSUE THREAD

**Issue by apjw-30** [benzman81/homebridge-http-webhooks#122]
Hi

Would love to see Music Speaker Support... 

- Play
- Pause
- Volume Up
- Volume Down
- Preset 1-5
- Next
- Previous

Thank you for considering...

**Comment by benzman81** [comment]
Pull requests welcome.

**Comment by jsiegenthaler** [comment]
@apjw-30 this won't actually work well (if at all) as the Apple implementation of a smart speaker assumes control is occurring over Airplay. Thus the speaker controls cannot be changed in HomeKit. @benzman81 I suggest closing this issue as it is 3 years old and cannot be implemented.

A possible method would be the implementation of the Apple Remote Control, which is totally feasible, but this is a separate topic :)

**Comment by benzman81** [comment]
Closed as suggested.
