### ISSUE TITLE
[HttpWebHooks] [ERROR Http WebHook Server] No accessoryId in request.

### ISSUE THREAD

**Issue by nrosa2002** [benzman81/homebridge-http-webhooks#123]
Here is an extract of my config and the http url I am using on a shelly device.
I keep receiving the error on the title.
Can someone help?
Thanks

http://10.xx.x.xxx:51828/?sensor1=Hallway Window Vibration&true=NEWSTATE
also tried http://10.xx.x.xxx:51828/?sensor1=sensor1&true=NEWSTATE

{
            "platform": "HttpWebHooks",
            "plugin_map": {
                "plugin_name": "homebridge-http-webhooks"
            },
            "sensors": [
                {
                    "id": "sensor1",
                    "name": "Hallway Window Vibration",
                    "type": "motion"
            ],
            "webhook_port": "51828",
    
        }

**Comment by benzman81** [comment]
As the readme states, your url must look like this:
`http://yourHomebridgeServerIp:webhook_port/?accessoryId=sensor1&state=true` or set false to deactivate ist.

**Comment by nrosa2002** [comment]
Many many thanks. I guess I had tried all alternatives but that one. Great!
