### ISSUE TITLE
NEWSTATE only works in one direction

### ISSUE THREAD

**Issue by Barry-Hurley** [benzman81/homebridge-http-webhooks#129]
Just a basic switch:
.../?accessoryId=switch1&state=true works ok.
.../?accessoryId=switch1&state=false works ok.

If the current state is true, then .../?accessoryId=switch1&state=newstate works ok and the switch is set to false.
If the current state is false, then .../?accessoryId=switch1&state=newstate does nothing and the switch stays false. No log event seems to be recorded.

I'm trying to use the same call to switch on and off, but I don't understand why newstate only works to switch off, and not back on again. 

Help?

**Comment by benzman81** [comment]
Can you show your config?

**Comment by Barry-Hurley** [comment]
The most basic config possible I imagine. 
    {
            "switches": [
                {
                    "id": "switch1",
                    "name": "switch1"
                }
            ],
            "platform": "HttpWebHooks"
        }

I have tried including all the optional lines, but same result. I've tried setting it to be a light, or an outlet, and still the same.

**Comment by benzman81** [comment]
@Barry-Hurley ah, now I get what you want. A toggle behavior is not possible. See Readme: `For switches the value for NEWSTATE is either true for on or false for off.` Feel free to make a pull request.

**Comment by Barry-Hurley** [comment]
Then I'm very confused, and fear I don't understand what this plugin is actually for!

I created a basic switch. I can turn the switch on or off using the dashboard GUI.

I can turn the switch on by entering the following command from anywhere on my network:
http://yourHomebridgeServerIp:webhook_port/?accessoryId=theAccessoryIdToTrigger&state=true

I can turn the switch off by entering the following command from anywhere on my network:
http://yourHomebridgeServerIp:webhook_port/?accessoryId=theAccessoryIdToTrigger&state=false

At any time, I can see the status of the switch by entering the following command from anywhere on my network:
http://yourHomebridgeServerIp:webhook_port/?accessoryId=theAccessoryIdToTrigger

From Readme: "To trigger a change of a boolean accessory you need to call the url http://yourHomebridgeServerIp:webhook_port/?accessoryId=theAccessoryIdToTrigger&state=NEWSTATE"
Calling that URL changes the state of the switch from true to false.
I expected that calling that URL again would then change the state of the switch from false back to true, and so on.
No?

I'm trying to use a single URL (stored in an NFC tag) as a trigger so that anybody on my network can switch on and off a light without needing access to the smart home itself. The light status is programmed to follow the switch status. I thought your plugin looked ideal for the job. If not, I would appreciate any advice you might have for alternate solutions. Thanks!

**Comment by benzman81** [comment]
Your stated sentence from the Readme is the general URL to trigger a change of a boolean accessory. The details sub section of this for a switch states, that NEWSTATE has either to be `true` for on or `false` for off.

The general purpose of this plugin is to create accessories that can be changed by an url, call an url on state changes and request the state by an url. That is also true for the switch and you already stated the valid urls to change and get the state in and from HomeKit. But there is no single url to toggle a boolean accessory, you have to call it with either `true` or `false`.

You should be able to use a pushbutton and automations to solve your problem. Create a pushbutton that does not call any url. Now, in Home/Eve/WhatEverAppYouUse create an automation, that trigger on the pushbutton state. As a condition you use "if light A is off" and as action you turn light A on. Then create a second url with condition "if light A is on" and as action you turn off light A. This way, you should be able to call the pushbutton url from your NFC always with `true` and the automations should be triggered as desired. Not tried, but should work.

**Comment by Barry-Hurley** [comment]
OK. Thanks for your time and insight. Greatly appreciated.
