### ISSUE TITLE
[ERROR Http WebHook Server] No accessoryId in request.

### ISSUE THREAD

**Issue by jaquesp** [benzman81/homebridge-http-webhooks#13]
Hello - I've started randomly getting these errors in my homebridge log. I haven't changed any configuration. Could you help me diagnose these further - how can I tell where the request is coming from and what the content (or lack of) is?

Thanks in advance,
Paul

**Comment by benzman81** [comment]
Hi, this only happens if there is a call to the server withmissing accessoryId as parameter.

**Comment by andyrooo82** [comment]
I had this issue too

https://github.com/benzman81/homebridge-http-webhooks/issues/11

**Comment by jaquesp** [comment]
@andyrooo82 Thanks for pointing this out, however I've turned off all possible automated calls to the webhook (via IFTTT) and still see this error. There is nothing calling the webhook at all, but still intermittently I will see a collection of calls and not just a single one, e.g.:

```
Feb 21 17:38:12 raspberrypi homebridge[30625]: [2/21/2017, 5:38:12 PM] [ERROR Http WebHook Server] No accessoryId in request.
Feb 21 17:38:12 raspberrypi homebridge[30625]: [2/21/2017, 5:38:12 PM] [ERROR Http WebHook Server] No accessoryId in request.
Feb 21 17:38:12 raspberrypi homebridge[30625]: [2/21/2017, 5:38:12 PM] [ERROR Http WebHook Server] No accessoryId in request.
Feb 21 17:38:12 raspberrypi homebridge[30625]: [2/21/2017, 5:38:12 PM] [ERROR Http WebHook Server] No accessoryId in request.
Feb 21 17:38:12 raspberrypi homebridge[30625]: [2/21/2017, 5:38:12 PM] [ERROR Http WebHook Server] No accessoryId in request.
Feb 21 17:38:12 raspberrypi homebridge[30625]: [2/21/2017, 5:38:12 PM] [ERROR Http WebHook Server] No accessoryId in request.
Feb 21 17:38:12 raspberrypi homebridge[30625]: [2/21/2017, 5:38:12 PM] [ERROR Http WebHook Server] No accessoryId in request.

Feb 21 17:38:13 raspberrypi homebridge[30625]: [2/21/2017, 5:38:13 PM] [ERROR Http WebHook Server] No accessoryId in request.
Feb 21 17:38:13 raspberrypi homebridge[30625]: [2/21/2017, 5:38:13 PM] [ERROR Http WebHook Server] No accessoryId in request.
Feb 21 17:38:13 raspberrypi homebridge[30625]: [2/21/2017, 5:38:13 PM] [ERROR Http WebHook Server] No accessoryId in request.

Feb 21 17:38:32 raspberrypi homebridge[30625]: [2/21/2017, 5:38:32 PM] [ERROR Http WebHook Server] No accessoryId in request.
Feb 21 17:38:32 raspberrypi homebridge[30625]: [2/21/2017, 5:38:32 PM] [ERROR Http WebHook Server] No accessoryId in request.
Feb 21 17:38:32 raspberrypi homebridge[30625]: [2/21/2017, 5:38:32 PM] [ERROR Http WebHook Server] No accessoryId in request.
Feb 21 17:38:32 raspberrypi homebridge[30625]: [2/21/2017, 5:38:32 PM] [ERROR Http WebHook Server] No accessoryId in request.
```

Is there anyway I can diagnose where the call is coming from - would there be anything in the debug that would help me track this down? As I say, nothing should be calling this now!

Thanks in advance,
Paul

**Comment by benzman81** [comment]
Hi, you can modify the plugin source to log the request information like caller ip. Did this once, but cant remember how i did this. Google helped me ;-)

**Comment by jaquesp** [comment]
So, here's what I did. I decided the first thing would be to work out where the request was coming from. I couldn't work out how to display the caller IP, so I added a source parameter to each of the calls I am making from IFTTT, e.g.:

`http://thisismyurl.net:51829/?accessoryId=ifttt_sensor1&state=true&source=ifttt_maker_applet`

and then modified the index.js to display this (in fact I uncommented an existing INFO line and added the source parameter to the display:

`this.log("[INFO Http WebHook Server] State change of '%s' to '%s'. Referrer: %s",accessory.id,stateBool,theUrlParams.source);`

Since I did this, I haven't yet seen an issue with a missing accessoryid - I'll be keeping an eye on it, and IF it happens I'll see an undefined source and will know I've missed a call. However, this was happening so regularly, I think that by somehow adding an additional parameter to the call (even if it's unused and purposeless) might resolve this issue...

I'll update in a few days if I see anything - but this might help someone down the line!

Thanks again for the tips.

**Comment by benzman81** [comment]
Did the issue occur since then?

**Comment by benzman81** [comment]
Not reproduceable.

**Comment by jaquesp** [comment]
No - i haven't seen this since. I don't fully understand why this has resolved the issue, but it has! thanks!
