### ISSUE TITLE
Missing "Pushbuttons" for Config-UI

### ISSUE THREAD

**Issue by thevangogh** [benzman81/homebridge-http-webhooks#140]
Hi all,
The Pushbuttons device type seems to be missing for Config UI schema.

**Comment by jsiegenthaler** [comment]
[config.schema.json](https://github.com/benzman81/homebridge-http-webhooks/blob/master/config.schema.json) has contains config for pushbuttons since a long time.

@benzman81 this issue can be closed, it is fixed

**Comment by benzman81** [comment]
Closed as already fixed.
