### ISSUE TITLE
Option to not wait for URL response

### ISSUE THREAD

**Issue by TeslaOwnerTips** [benzman81/homebridge-http-webhooks#146]
An option to have the button change state immediately and respond to Homekit without waiting for the URL response.

**Use case:**
A Tesla goes to sleep. When asleep it does not respond till it wakes up.
TeslaFi has an API that allows us to sent a command after it waits for Tesla to wake up but does not respond till this is completed.
http://$URL/?command=flash_lights&wake=30

**Comment by benzman81** [comment]
Why should this be needed? The command is executed and homekit will report the status after the response was returned. If you ignore tbe respones you would not receive failures and always assume success.

**Comment by TeslaOwnerTips** [comment]
I explained it?
Anyway I’ll close it.
