### ISSUE TITLE
EACCES error when running via launchd on macOS

### ISSUE THREAD

**Issue by xer099** [benzman81/homebridge-http-webhooks#15]
When I run via terminal everything works, but  get an EACCES error when running as a daemon via launchd.  See log below.  Any thoughts on how to run as a daemon?

>  [2017-8-22 22:07:31] Initializing HttpWebHooks platform...
> /usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/mkdirp/index.js:90
>                     throw err0;
>                     ^
> 
> Error: EACCES: permission denied, mkdir '/~/.node-persist'
>     at Object.fs.mkdirSync (fs.js:891:18)
>     at sync (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/mkdirp/index.js:71:13)
>     at Function.sync (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/mkdirp/index.js:77:24)
>     at LocalStorage.parseStorageDirSync (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/local-storage.js:600:20)
>     at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/local-storage.js:141:14)
>     at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/node-persist.js:37:32)
>     at HttpWebHooksPlatform (/usr/local/lib/node_modules/homebridge-http-webhooks/index.js:25:18)
>     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:32)
>     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
>     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
>     at Module._compile (module.js:573:30)
>     at Object.Module._extensions..js (module.js:584:10)
>     at Module.load (module.js:507:32)
>     at tryModuleLoad (module.js:470:12)
>     at Function.Module._load (module.js:462:3)

**Comment by benzman81** [comment]
You should point the "cache_directory" to a directory the user has permission to or give the user the required permission.

See https://github.com/benzman81/homebridge-nukiio/issues/11
