### ISSUE TITLE
Success criteria

### ISSUE THREAD

**Issue by TeslaOwnerTips** [benzman81/homebridge-http-webhooks#153]
Curious why when incorrect value types (numeric/boolean) or out or range values are provided the response has "success":true

Basically except for an id not found the response is always "success":true

[ERROR Http WebHook Server] AccessoryId 'locked' not found

**Comment by benzman81** [comment]
This is simply because I think it is not needed and adds unnecessary complexity which should be only needed to "setup" the hooks correctly. If they are configured and called correctly, the this should never happen or shouldn't be a problem.
