### ISSUE TITLE
Contact sensors unresponsive

### ISSUE THREAD

**Issue by Miq313** [benzman81/homebridge-http-webhooks#155]
I have a few contact sensors that do not switch states with the URL call. I receive a `{"success":true}` response and the logs show that my URL call was processed, yet the sensors don't actually change state.

Is there any way to troubleshoot this? Is anyone experiencing similar issues?

**Comment by benzman81** [comment]
What does the url you call look like?
What is printed in the homebridge log while you call the url?

**Comment by Miq313** [comment]
my URL calls look like `http://[hostname].local:8583/?accessoryId=sensor1&state=false`, and the homebridge log has the following entry: `{"key":"http-webhook-sensor1","value":false}`

I've tested with other boolean sensors (occupancy & motion) and they work perfectly, the issue only exists with the contact sensor.

**Comment by benzman81** [comment]
Please start homebridge with debug mode an post the log.

https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting#debug-mode

**Comment by benzman81** [comment]
Closed due to lack of response.
