### ISSUE TITLE
Motion Sensor Not Sending Notifications

### ISSUE THREAD

**Issue by alexclst** [benzman81/homebridge-http-webhooks#156]
I've set up a motion sensor with this plugin. As I understand it, and settings exist within the Home app to enable this, we should be able to receive activity notifications for sensors. Yet even with such notifications enabled for a sensor configured with this plugin as a `motion` sensor, no notifications are sent. Is this a problem on my end, or does this plugin simply not (yet) support sending activity notifications in HomeKit?

**Comment by jsiegenthaler** [comment]
Does the motion sensor work? Is it correctly showing motion and no motion? 

The notifications are managed by the Home hub, not the plugin.  The plugin cannot disable notifications.

**Comment by alexclst** [comment]
I tested again this morning, using curl to poke the API, and today I got notifications. So, yeah, maybe something strange was up with the hubs in my house?
