### ISSUE TITLE
POST request

### ISSUE THREAD

**Issue by genfersee** [benzman81/homebridge-http-webhooks#158]
Hello all,

I am trying to configure a POST request within a pushbutton.

Such POST request works well with curl this way:
`curl -X POST -d 'api_key=1234' https://unlocator.com/tool/api.php`

But my pushbutton configuration does not work:
```
         {
                    "id": "pushbutton2",
                    "name": "Unlocator",
                    "push_url": "https://unlocator.com/tool/api.php",
                    "push_method": "POST",
                    "push_body": "{ \"api_key\": \"1234\" }"
                }
```

The servers says:
```
[19.03.2022, 22:47:58] [HttpWebHooks] Adding Body { "api_key": "1234" }
[19.03.2022, 22:47:59] [HttpWebHooks] Request to 'https://unlocator.com/tool/api.php' finished with status code '200' and body 'Missing or Invalid API Key'. null
```

Seems the server does not recognise the body I am sending.

Any idea what is wrong?

Thanks a lot :)

**Comment by benzman81** [comment]
Maybe it doesnt accept json. 

Try `"push_body": "api_key=123`.

**Comment by genfersee** [comment]
Hello! Thanks for your quick answer!
Unfortunately it says the same:

```
                {
                    "id": "pushbutton2",
                    "name": "Unlocator",
                    "push_url": "https://unlocator.com/tool/api.php",
                    "push_method": "POST",
                    "push_body": "api_key=1234"
                }
```

```
[19.03.2022, 23:10:09] [HttpWebHooks] Adding Body api_key=1234
[19.03.2022, 23:10:10] [HttpWebHooks] Request to 'https://unlocator.com/tool/api.php' finished with status code '200' and body 'Missing or Invalid API Key'. null
```

**Comment by genfersee** [comment]
And the POST request also works this way, when configured in iOS shortcut (sorry for the french):
We see there is no header.

<img width="632" alt="Capture d’écran 2022-03-19 à 23 19 45" src="https://user-images.githubusercontent.com/37344815/159140396-0389ae7c-b36a-4d54-9569-3497f1574bd7.png">

**Comment by genfersee** [comment]
Hi @benzman81 
I did some try with Postman to see how the server reacts and I manage to have a config which works great:

 ```
               {
                    "id": "pushbutton2",
                    "name": "Unlocator",
                    "push_url": "https://unlocator.com/tool/api.php",
                    "push_method": "POST",
                    "push_form": "{\"api_key\" : \"1234\" }",
                    "push_headers": "{\"Content-Type\": \"application/x-www-form-urlencoded\"}"
                }
```

Thanks again for your support ;)
