### ISSUE TITLE
Occupancy sensor doesn't update in v0.1.16

### ISSUE THREAD

**Issue by jebeezer** [benzman81/homebridge-http-webhooks#166]
I've been using this plugin to several automations using the switches and I've used now the occupancy sensor for the first time.
When using the http command, the sensor doesn't change stated, when using v0.1.16. I've downgraded to v0.1.15 and the http command works fine. I've tried some other sensors and the same happens (exception is leak sensor that works in v0.1.16, bur maybe because it uses a different command).
Anyone experiencing the same in v0.1.16?

**Comment by benzman81** [comment]
@jebeezer I use the sensors myself and they update just fine using `http://myhomebridgeip:myhomebridgeport/?accessoryId=myoccupancy&state=true` or `http://myhomebridgeip:myhomebridgeport/?accessoryId=myoccupancy&state=false`.

**Comment by jebeezer** [comment]
Thank you. I've upgraded again to v0.1.16 and its working fine. Do you think it could be a cache issue? I was trying the different sensor types, keeping the same name and only restarting Homebridge, when I realised the sensor was not updating by the http command. After downgrading it started working so I jumped into a conclusion that v0.1.16 had some type of issue.

**Comment by benzman81** [comment]
No clue :-) I restart homebridge every night and the states get always updated correctly.

**Comment by jebeezer** [comment]
Thanks anyway! I will close this issue and good suggestion to restart home bridge daily!
