### ISSUE TITLE
Disabling callback to url, when change is detected.

### ISSUE THREAD

**Issue by cis2131** [benzman81/homebridge-http-webhooks#17]
I use this great plugin to send on and off events to a http based home control unit.

When the status on the control unit changes, i send a update to webhooks.

That works fine, but then it looks like webhhoks calls the on or off url, so the controller gets the same value once more.
Most of the time this works fine, but the unit is a bit slow, so sometimes this gives unwanted results.

Can you help me with how to disable this callback?.

**Comment by benzman81** [comment]
Not sure how this can happen. If you can reproduce the issue, try making some log statements in the plugin, otherwise I have mo idea how I can help :-(

**Comment by cis2131** [comment]
Thanks for getting back to me..

Here is some log..
[11/2/2017, 7:17:36 AM] [HttpWebHooks] Change HomeKit state for switch to 'false'.
[11/2/2017, 7:17:36 AM] [HttpWebHooks] Switch state for '0x9055b'...
[11/2/2017, 7:17:37 AM] [HttpWebHooks] Request to '[object Object]' finished with status code '200' and body 'ID: 591195'. null
[11/2/2017, 7:40:56 AM] [HttpWebHooks] Change HomeKit state for switch to 'false'.
(In this example, I haven't touched anything in the home app)

The control unit has detected a change, and i have then sent a Trigger change webhook request. In the fiirst line i see this request, which gets registeret in homekit.

Then the plugin sends a off command to the offurl (I can see that because the offurl returns ID: 591195, which is the decimal value of 0x9055b that is the name of the switch).

Hope it makes sense, otherwise say so, and i wil try to explain it in more detail.

**Comment by cis2131** [comment]
Hi Markus

I have now tested some more, and looked at your code.
I am getting more and more sure that your on and off function is also being called on the newstate event.
After reading the Readme several times, I might think that this is by design.
I first thought that newstate was only the value in homekit, that got changed but i see now that it is  more like a override of the button in homekit.
unfortunally I am not good enough in Javascript, to figure out how to change this behavior, could you help out?.. 
What I would like, is to change is so it don't send the states (on_url and off_url), when newstate is called (It should only update the value in homekit).
Pushing buttons in homekit, should off cause still call the url's

Hope you can help.

**Comment by cis2131** [comment]
Thanks for this fix.. Works fine.

Is it possible to add lights as well (Just like switches, but so they apear as lights in homekit).

**Comment by benzman81** [comment]
Could you create a new issue for this?
