### ISSUE TITLE
Log Output for Occupancy Sensor

### ISSUE THREAD

**Issue by shep1976** [benzman81/homebridge-http-webhooks#173]
Hi there,

Is there a way to get more verbose logging output on which Occupancy Sensor was triggered.  Currently I see this

08/11/2022, 23:02:15Http Webhooks BridgeHttpWebHooksChange HomeKit value for occupancy sensor to 'true'.
08/11/2022, 23:06:42Http Webhooks BridgeHttpWebHooksChange HomeKit value for occupancy sensor to 'false'.

It would be nice to see which exact sensor has been activated (Paul-Sensor for example).  I have debugging turned on, on the bridge itself but nothing extra is shown.

Thanks

Paul

**Comment by benzman81** [comment]
Feel free to add a PR.

**Comment by jsiegenthaler** [comment]
Resolved in PR #208

**Comment by benzman81** [comment]
solved by #208, will be released in 0.1.19
