### ISSUE TITLE
Celcius vs Fahrenheit Issue

### ISSUE THREAD

**Issue by dad2boyz** [benzman81/homebridge-http-webhooks#176]
I'm using this to update the information from a temperature sensor, via AquaSpace.  I see nowhere on either side to specify the unit as C or F.  Aquaspace is providing in F.  It appears the webhook is interpreting this as C.  Then homebridge converts to F.  So a temperature of 66.1 is displayed as 151.

Is there a flag I'm missing somewhere?

Thanks.

**Comment by benzman81** [comment]
Yes, homekit only works with degree celsius. If fahrenheit valis are provided it has to be converted somewhere outside of homekit.
Feel free to add a pull request to add support for it to the plugin if it is not possible to change in aquaspace.

**Comment by jsiegenthaler** [comment]
@benzman81 I think this can be closed as it's been over a year with no feedback

**Comment by benzman81** [comment]
Closed due to inactivity.
