### ISSUE TITLE
Fan state errors

### ISSUE THREAD

**Issue by TeslaOwnerTips** [benzman81/homebridge-http-webhooks#179]
I kept getting a state NaN error. 
I fixed this by using 0 & 1 instead of true & false. 

Further setting the speed without setting the state produced sate NaN errors. 

I fixed this by settling both speed and state in a single URL. 

speed=0&state=0
speed=33&state=1 
(any value >= 0 works)

Here are my tests
**Speed alone**
http://mac-mini.local:51828/?accessoryId=Wo&speed=4 {"success":true}
[7/16/2023, 12:53:06 AM] [homebridge-http-webhooks] 
_Change state for fanv2 to 'NaN'._

[7/16/2023, 12:53:06 AM] [homebridge-http-webhooks] 
_Change speed for fanv2 to '4'._

**Speed=4&state=true**
http://mac-mini.local:51828/?accessoryId=Wo&speed=4&state=true {"success":true}
[7/16/2023, 12:55:08 AM] [homebridge-http-webhooks] 
_Change state for fanv2 to 'NaN'._

[7/16/2023, 12:55:08 AM] [homebridge-http-webhooks] 
_Change speed for fanv2 to '4'._

**State alone**
http://mac-mini.local:51828/?accessoryId=Wo&state=false {"success":true}
[7/16/2023, 12:57:42 AM] [homebridge-http-webhooks] 
_Change state for fanv2 to 'NaN'._

[7/16/2023, 12:57:42 AM] [homebridge-http-webhooks] 
_Change speed for fanv2 to '0'._

**speed=33&state=0**
http://mac-mini.local:51828/?accessoryId=Wo&speed=33&state=0 {"success":true}
[7/16/2023, 12:59:39 AM] [homebridge-http-webhooks] 
_Change state for fanv2 to '0'._

[7/16/2023, 12:59:39 AM] [homebridge-http-webhooks] 
_Change speed for fanv2 to '33'._

**speed=33&state=1**
http://mac-mini.local:51828/?accessoryId=Wo&speed=33&state=1 {"success":true}
[7/16/2023, 1:00:22 AM] [homebridge-http-webhooks] 
_Change speed for fanv2 to '33'._

**Comment by TeslaOwnerTips** [comment]
**speed=33&state=0**
http://mac-mini.local:51828/?accessoryId=Wb&speed=0&state=0
_[7/16/2023, 2:07:47 AM] [homebridge-http-webhooks] _
Change state for fanv2 to '0'.
_[7/16/2023, 2:07:47 AM] [homebridge-http-webhooks] _
Change speed for fanv2 to '33'.

**Comment by TeslaOwnerTips** [comment]
If this is how it is supposed to work would you like me to update the documentation and submit a pull request?

**Comment by benzman81** [comment]
That would be great.

**Comment by benzman81** [comment]
closed with #184
