### ISSUE TITLE
no temperature in sensor device

### ISSUE THREAD

**Issue by Coolant22** [benzman81/homebridge-http-webhooks#185]
I have this in Homebridge-Protokoll :

Change HomeKit value for temperature sensor to 'NEWVALUE22.13'. , when the sensor to warm is a other value , also it works .
Change HomeKit value for temperature sensor to 'NEWVALUE24.81'

Also the temperature is in Homebridge , but not in the sensor device . In the device is 0. 
can you help me , what can I do , thanks Jens

**Comment by benzman81** [comment]
could you post your config and logs?

**Comment by jsiegenthaler** [comment]
@benzman81 It's been over a year and no feedback, I think this issue can be closed

**Comment by benzman81** [comment]
Closed due to inactivity.
