### ISSUE TITLE
Adding switch or pushbutton causes errors

### ISSUE THREAD

**Issue by nickjmassa** [benzman81/homebridge-http-webhooks#186]
Hi, I am using webhooks to recieve notifications from a shelly sensor on a garage door that works great. 

In attempting to add switches or buttons to **send** instructions to another shelly, I have noticed that adding a switch or pushbutton to an existing webhooks setup (shown below) causes the devieces in homekit to stop responding, until i remove them from the homekit config. 

If I create all the devices I need in the homebridge config, then add the child bridge to homekit, homekit says that the bridge/accessories are not compatible and cannot be added.

There are no logs in the homebridge home page that point to the issue.

{
            "webhook_port": "51828",
            "webhook_listen_host": "10.0.4.253",
            "sensors": [
                {
                    "id": "input0",
                    "name": "northgaragedoor",
                    "type": "contact"
                },
                {
                    "id": "input1",
                    "name": "centergaragedoor",
                    "type": "contact"
                },
                {
                    "id": "input2",
                    "name": "southgaragedoor",
                    "type": "contact"
                }
            ],
            "pushbuttons": [
                {
                    "id": "pushbutton0",
                    "name": "southgaragedoortrigger",
                    "push_url": "http://10.0.4.242/relay/0?turn=on"
                },
                {
                    "id": "pushbutton1",
                    "name": "centergaragedoor",
                    "push_url": "http://10.0.4.242/relay/1?turn=on"
                },
                {
                    "id": "pushbutton2",
                    "name": "northgaragedoor",
                    "push_url": "http://10.0.4.242/relay/2?turn=on"
                }
            ],
            "platform": "HttpWebHooks"
        }

**Comment by benzman81** [comment]
Shouldn't be a problem, maybe you create a cycle somehow? for example if your shelly notifies home bridge and home bridge shroud notify shelly. Then this could be a cycle. What das the log say?

**Comment by nickjmassa** [comment]
Never got to the bottom of this, but I think the homekit error it may have been that the "name" for the sensors and pushbuttons were the same.
