### ISSUE TITLE
Triggering via URL request will not work!

### ISSUE THREAD

**Issue by sysista** [benzman81/homebridge-http-webhooks#194]
...hey, i have successfully setup a Lightswitch in the plugin interface, if i press the button in the HB-UI the Button and the Light goes on, nice! But when i do this with the Trigger URL, only the Button in the UI goes "on" and the physical lights stay off.

Is this  a known configuration error or a bug? 

Thanks in advance

**Comment by benzman81** [comment]
sorry for late response, I am very busy currently. There is no bug known at this point. Maybe double check your configuration.

**Comment by jsiegenthaler** [comment]
@benzman81 I think this issue can be closed due to lack of feedback

**Comment by benzman81** [comment]
Closed due to inactivity.
