### ISSUE TITLE
Question:  Can this be used to trigger a Sonos playlist?

### ISSUE THREAD

**Issue by crosspjc** [benzman81/homebridge-http-webhooks#2]
Could I use this with https://github.com/jishi/node-sonos-http-api to trigger playlists etc?

**Comment by benzman81** [comment]
You might use a switch for one or the other action, but I think for playlists "swith" might not be the correct accessesory. Personally I use https://www.npmjs.com/package/homebridge-sonos, but it can not handle playlists. There are some forks that support it though.
