### ISSUE TITLE
Webhook callback problem

### ISSUE THREAD

**Issue by cis2131** [benzman81/homebridge-http-webhooks#20]
I tested 0.0.25, for the issue where a webhook change would trigger a on/off event. And at first glance i thought that your change solved the issue.

But after further investigation (Testing on 0.0.26). I can see that it don't seem to solve the problem anyway.

The way it behave right now can cause a loop between homekit and my home control system.
The reason for this is that when my home controller sends a webhook change, your program seems to update homekit, and then send the on/off  url command.

Is it possible to add an option to the webhook, so it only updates homekit, but don't send the on/off url calls. I know that it propably is not what this plugin was intended for, but maybe it could be a nice feature for this plugin, so it can be used for reflecting states of another system in homekit.

**Comment by benzman81** [comment]
Can you make a bit more clear what requests are sent by who and what the current behavior looks like and what is the desired behavior?

**Comment by cis2131** [comment]
I have a program that listens to my home controller for changes in light states.

When i detect a change (e.g. when a light gets turned on), i send a webhook to your plugin, so the change is also reflected in homekit.

The on events from your plugin gets sent to the home controller, which then turns on the light.

When that happens, my program detects the change, and sends it back to your plugin via webhook. 
Your plugin then updates homekit, and sends the on event to the controller once more, causing a loop.

What i would like, is to be able to send the status via webhook call to your plugin, but only updating the change in homekit, without sending it back to the controller. 
It could be like an option to the webhook call (eg. &UpdateOnly=true).

Hope it makes sense..

**Comment by benzman81** [comment]
Yeah, got you. Well, first I want to tell you, that a button/light does not need to haven an on/off url. If you just want those reflecting the states, remove the urls. Second, thinking about the code, it seems to me that actually a webhook should never run the url request, as in most cases the call will come from another smart home device to update the state. So, there should be no need to send on/off url back to that system as it already knows the state. I will think more about it and might change it pretty soon.

**Comment by benzman81** [comment]
Fixed with v0.0.27.
