### ISSUE TITLE
Configuration issue with homebridge 1.7.0 / hoobs 4.3.1

### ISSUE THREAD

**Issue by StefanHaefliger24** [benzman81/homebridge-http-webhooks#200]
Hi there,
I just struggled with the configuration of this plugin on homebridge 1.7.0 / hoobs 4.3.1.

Following Configuration was requried to create a motion device. The thing is, if clicked on "configuration" on the plugin, only the second part (homebridge-http-webshooks" is shown... but the sensors need to be configured unter the HttpWebHooks section - which is only available in the "Advanced" section.

    "accessories": [],
    "platforms": [
        {
            "platform": "HttpWebHooks",
            "sensors": [
                {
                    "id": "motion1",
                    "name": "Motion 1",
                    "type": "motion"
                }
            ]
        },
        {
            "platform": "homebridge-http-webhooks"
        }
    ]

With my "old" hoobs (3.3.5) this was working fine, there was even a graphical interface for the configuration. 
still not sure wether this is a plugin issue or something I would need to address with hoobs?

someone with the same expierence?

**Comment by jsiegenthaler** [comment]
My very first comment would be why are you using such an old version of Homebridge? Current version is v1.8.4. Update Homebridge then try again.
