### ISSUE TITLE
URL not triggering the switch

### ISSUE THREAD

**Issue by fordstone** [benzman81/homebridge-http-webhooks#202]
I am sure this is an error on my part. 
I set up a switch using the UI and plugin config. 
It shows up under accessories. 
I can successfully access the "on" or "off" URLs using CURL or a browser. 
This has no effect on the switch itself. Nothing shows up in the log. 
I am on V 0.1.18 and Homebridge V 1.8.5. 
Am I missing a step?
Thanks in advance.

**Comment by jsiegenthaler** [comment]
I use this plugin and it works perfectly. Share your urls you use to turn in an off. Make sure it controls the accessory as viewed in Homebridge. If that works then there is no reason for it not to work in HomeKit

**Comment by fordstone** [comment]
"onUrl": "http://localhost:51828/?accessoryId=pumpSwitch&state=1",
                  "offUrl": "http://localhost:51828/?accessoryId=pumpSwitch&state=0"

As of now, I have not attached it to the existing accessory because 
a) I do not know how to do that yet 
b) I was trying to test this switch to limit the number of variables. 

Is this the problem?

**Comment by jsiegenthaler** [comment]
You misunderstand. The accessory is the virtual device that gets created from the web hooks plugin. You can view it in Homebridge > Accessories. If you configured a switch, then a switch will be visible. Make sure it is visible and reacts to the url commands. 

Your URLs need to use the text true or false, not 1 or 0

**Comment by fordstone** [comment]
That did it! Changing to true and false! Thanks so much!!
