### ISSUE TITLE
Integration with existing switch

### ISSUE THREAD

**Issue by fordstone** [benzman81/homebridge-http-webhooks#203]
Looking for some assistance. I may be using this plug-in incorrectly. I am able to successfully create a new switch, and control that switch with the http. This is essentially a "dummy" switch as it does not attach to anything. I am unable to trigger my existing api switch. I tried giving everything the same name and id to see if that would help, to no avail. Here is a sample of the relevant section of my config

      "id": "poolswitch",
      "name": "poolswitch",
      "BaseURL": "https://api.smartthings.com/v1/",
      "AccessToken": "**edited**",
      "GarageDoorMaxPoll": 40,
      "PollLocksSeconds": 10,
      "PollDoorsSeconds": 10,
      "PollSensorsSeconds": 5,
      "PollSwitchesAndLightsSeconds": 10,
      "PollWindowShadesSeconds": 20,
      "ExposeHumiditySensorForAirConditioners": false,
      "OptionalModeForAirConditioners": "None",
      "IgnoreLocations": [
        "Pool"
      ],
      "platform": "HomeBridgeSmartThings"
    },
    {
      "webhook_port": 51828,
      "webhook_listen_host": "::",
      "webhook_enable_cors": true,
      "https": false,
      "switches": [
        {
          "id": "poolswitch",
          "name": "poolswitch",
          "on_url": "http://localhost:51828/?accessoryId=poolswitch&state=true"
        }
      ],
      "platform": "HttpWebHooks"

**Comment by jsiegenthaler** [comment]
You config is wrong. The on_url is what the switch will trigger when it is turned on. You have it triggering itself.
Here's my config as an example (ip addresses removed):
{
  "id": "whFamilyPresentSwitch",
  "name": "Family Present",
  "on_url": "http://xxx.xxx.xxx.xxx:51828/?accessoryId=whFamilyOccupancy&state=true",
  "off_url": "http://xxx.xxx.xxx.xxx:51828/?accessoryId=whFamilyOccupancy&state=false"
},
This means that when the whFamilyPresentSwitch turns on, it calls the on_url which sets then whFamilyOccupancy to true
And when the whFamilyPresentSwitch turns off, it sets the whFamilyOccupancy to false.

You have your poolswitch calling itself to switch itself on when it turns on, which does not make any sense.
If you don't have anything to trigger via url, then leave the on_url blank (or delete it from the config)

The above switch triggers my family occupancy sensor which is configured as:
{
  "id": "whFamilyOccupancy",
  "name": "Family At Home",
  "type": "occupancy"
},

For some of my webhooks switches, I just use a very simple config as I don't need to trigger anything via url 
{
  "id": "whOutsideLightControl",
  "name": "Outside Light Switch"
},

**Comment by jsiegenthaler** [comment]
And when you say "I am unable to trigger my existing api switch", what are you referring to? 
What is the url of the api you wish to trigger? 
If you know the url, test it in a web browser. When you confirm it works in the webbrowser, add it to the on_url or the off_url as desired

**Comment by fordstone** [comment]
The top poolswitch with the API (with the platform HomeBridgeSmartThings) was an existing switch that literally turns my pool on or off via homekit. What I was trying to accomplish here is being able to trigger that switch on or off using the associated URLs via a simple python script in order to turn the pool on or off during certain conditions. I created the second switch (platform HttpWebHooks) to test the concept and it works great. The issue I am describing now is that I am only able to control a switch that was created in HttpWebHooks and I can not figure out how to modify the HomeBridgeSmartThings switch or give it a URL via HttpWebHooks plugin.

**Comment by jsiegenthaler** [comment]
To link the two currently independent switches together, use a HomeKit automation.
If you only want to control via a url, then just add:
When WebHooks poolswitch turns On, turn on HomeBridgeSmartThings poolswitch
When WebHooks poolswitch turns Off, turn off HomeBridgeSmartThings poolswitch

If you want the Webhooks switch to show the same state as the HomeBridgeSmartThings , then add:
When HomeBridgeSmartThings poolswitch turns On, turn on WebHooks poolswitch
When HomeBridgeSmartThings poolswitch turns Off, turn off WebHooks poolswitch

Then you can call the url to run on or off the webhooks switch, which in turn turns on or off the HomeBridgeSmartThings switch

Tip: you will find this MUCH easier to manage if you give the two switches different names :)

**Comment by fordstone** [comment]
Thanks so much for your help. I have changed the names as you suggested. I was hoping to accomplish my task within HomeBridge itself, as I do not have a Home Hub. It sounds like this may be overreaching the possibilities of HomeBridge, this plugin, or any plugin that I can find.

**Comment by jsiegenthaler** [comment]
Well, you can also call the url of the Homebridge accessory directly to control a characteristic on it. A bit more involved, but totally possible, as long as the accessory is in Homebridge.
See http://192.168.0.100:8581/swagger#/Accessories/AccessoriesController_setAccessoryCharacteristic
It is a PUT command with a body, so you need to form that properly first. And you need to get the UUID for the accessory.

My note about using HomeKit automation works for every HomeKit accessory, regardless of how it is added to HomeKit.
This note about controlling the Homebridge accessory directly works only for accessories in Homebridge.

**Comment by jsiegenthaler** [comment]
@benzman81 I thing this Issue can be closed due to lack of feedback and given that it was a user config issue
