### ISSUE TITLE
Push button cached state not being released 

### ISSUE THREAD

**Issue by BetoRn** [benzman81/homebridge-http-webhooks#23]
Calling the web hook for a push button works the 1st time, then the “true” state is cached on the node_persist/storage directory
I have to change it to false manually in order to make it work again

**Comment by benzman81** [comment]
@BetoRn Could you check if its is fixed with new version?

**Comment by BetoRn** [comment]
@benzman81 now it crashes:

Feb 26 16:53:25 raspberrypi homebridge[14196]: [2/26/2018, 4:53:25 PM] [HttpWebHooks] Change HomeKit state for push button to 'true'.
Feb 26 16:53:26 raspberrypi homebridge[14196]: /usr/lib/node_modules/homebridge-http-webhooks/index.js:409
Feb 26 16:53:26 raspberrypi homebridge[14196]: this.storage.setItemSync("http-webhook-" + this.id, false);
Feb 26 16:53:26 raspberrypi homebridge[14196]: ^
Feb 26 16:53:26 raspberrypi homebridge[14196]: TypeError: Cannot read property 'setItemSync' of undefined
Feb 26 16:53:26 raspberrypi homebridge[14196]: at HttpWebHookPushButtonAccessory.<anonymous> (/usr/lib/node_modules/homebridge-http-webhooks/index.js:409:21)
Feb 26 16:53:26 raspberrypi homebridge[14196]: at ontimeout (timers.js:386:14)
Feb 26 16:53:26 raspberrypi homebridge[14196]: at tryOnTimeout (timers.js:250:5)
Feb 26 16:53:26 raspberrypi homebridge[14196]: at Timer.listOnTimeout (timers.js:214:5)
Feb 26 16:53:26 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Feb 26 16:53:26 raspberrypi systemd[1]: Unit homebridge.service entered failed state.

**Comment by benzman81** [comment]
sorry, was a blind fix. Now I had time to test it. Now works.
