### ISSUE TITLE
Case sensitive key "accessoryId" in Trigger URL

### ISSUE THREAD

**Issue by squipswd** [benzman81/homebridge-http-webhooks#24]
I am not able to send accessoryId with capital I
The client application sends all URLs in lowercase.
Is there an parameter for case insensitivity? 
Thanks
Wolfgang

**Comment by benzman81** [comment]
Sorry for late response. There is no parameter for this. The specification a the query inside the url does not  define anything for case in/sensitivity. Your client should be able to send all cases. I wouldnt want to add this handling just becaude one client does not support it as I would have to handle both cases for backwards compatibility that adds extra complexity.
