### ISSUE TITLE
Stateless Programmable Switch

### ISSUE THREAD

**Issue by dinmammas** [benzman81/homebridge-http-webhooks#32]
Hi!
Thanks for an awesome plug-in! :) 👍 

Would it be possible to add support for the Stateless Programmable Switch service type?
https://github.com/KhaosT/HAP-NodeJS/blob/9eaea6df40811ccc71664a1ab0c13736e759dac7/lib/gen/HomeKitTypes.js#L3384

TIA,
David

**Comment by dinmammas** [comment]
Sorry, realized you'd been asked this before...

**Comment by dinmammas** [comment]
It's here. https://github.com/benzman81/homebridge-http-webhooks/issues/8

I'll see what I can do. ;)

**Comment by benzman81** [comment]
Merged by #38
