### ISSUE TITLE
Garage Door

### ISSUE THREAD

**Issue by Red1994** [benzman81/homebridge-http-webhooks#33]
I currently have a wifi momentary relay to activate a garage door by url trigger (using webhooks pushbutton) and a wifi sensor attached to the garage door to send url status (using webhooks sensor). Would it be possible to combine the webhooks sensor function with the webhooks push button function into a webhooks garage door function (with a single open/close status and push to trigger garage door icon in homekit)?  I have seen this combined function in the homebridge wemo plugin for the wemo relay.

thanks

**Comment by benzman81** [comment]
Garage door is now supported due to #34
