### ISSUE TITLE
Feature Request: Ask for current state

### ISSUE THREAD

**Issue by dkrizic** [benzman81/homebridge-http-webhooks#4]
Hi, 

is there a way to ask for the current state? If not, please add this feature. Maybe if "state=" is omitted.

Regards

**Comment by benzman81** [comment]
Not yet, but should be easy to implement. I will add it in the next couple of days.

**Comment by benzman81** [comment]
Implemented and published with v0.0.21.

**Comment by dkrizic** [comment]
Thanks, I will test it and give feedback
