### ISSUE TITLE
Can't send Temperature URL

### ISSUE THREAD

**Issue by YannickHaas** [benzman81/homebridge-http-webhooks#44]
Hello, 
I can't send a temperature to my Temperature-sensor.

URL: 
http://192.168.178.XXX:51828/?accessoryId=sensor1&value=20

What is the correct format for value?

**Comment by Rob-VF** [comment]
Have you tried with CURL command by command line?

**Comment by benzman81** [comment]
please post the anonymized home bridge log after calling the url

**Comment by benzman81** [comment]
closed asm there was no response. testing shows its working.
