### ISSUE TITLE
body as string

### ISSUE THREAD

**Issue by xdenneboom** [benzman81/homebridge-http-webhooks#45]
Hi, 

I have a JSON body that I want to include in a POST request, but since the body needs to be a string, this is messing up my config. Can we allow the body as an object?

**Comment by matteodisabatino** [comment]
@benzman81 sorry to bother, are there news on that?

**Comment by benzman81** [comment]
@matteodisabatino feel free to provide a tested pull request.

**Comment by BetoRn** [comment]
@xdenneboom, @matteodisabatino the example provided for the body is a JSON but it's wrong, needs to be like this:

"on_body": "{\"on\":true}"

sorry about that.

**Comment by BetoRn** [comment]
ohh wait! I can't post it correctly, here you have a snapshot of my config

![image](https://user-images.githubusercontent.com/14804764/53467519-2eca0e80-3a1c-11e9-8567-498871a997bf.png)

**Comment by EddyK69** [comment]
Added PR #66 to add the functionality to add JSON to the form-header...

**Comment by benzman81** [comment]
fixed by #66
