### ISSUE TITLE
support commands additional to urls

### ISSUE THREAD

**Issue by Rob-VF** [benzman81/homebridge-http-webhooks#46]
Hello, may I suggest to add also commands (curl, php etc) not only http requests to turn on or off elements on homekit? As the plugin homebridge-cmdSwitch2 works, it could be great to have "on_cmd" and "off_cmd" instead of "on_url" and "off_url", a mix between commands and webhooks for notifications could be awesome.
Thanks

**Comment by benzman81** [comment]
What would be a use case? You already mentioned a plugin that does this.

**Comment by Rob-VF** [comment]
Hello Markus,

the idea is to allow the interfacing towards applications where no http API is allowed, and let that application to update the object status using http.

An example:

homebridge ———>  shell command ———> object to control

then

object controlled ———> http url to update ———> hombebridge updated


R

**Comment by jsiegenthaler** [comment]
@benzman81 : the http-webhooks is a plugin for http webhooks, not for executing shell commands. There are other plugins that execute shell commands, and do it well. I recommend that this issue be regarded as not a suitable feature for a webhooks plugin, as Cmd2 (and also Cmd4) provide these functions well, and thus that this issue be closed.
