### ISSUE TITLE
statelessswitches can not call urls

### ISSUE THREAD

**Issue by suxus-zz** [benzman81/homebridge-http-webhooks#48]
Hello

I will try to use the statelessswitch for Sonos (API) volume.

Example: http://192.168.1.xxx:5005/office/volume/+5

but how can set the event in the statelessswitches?

 "statelessswitches": [
   {
      "id": "statelessswitch1",
      "name": "Stateless Switch 1",
      "buttons":[ //the buttons of the switch
      {
         "name": "Button1"
       },
       {
          "name": "Button2",
          "double_press": false, //you can disable a type of action
          "long_press": false
       }
       ]
   }
],

Greeting

**Comment by benzman81** [comment]
It is not implemented to call URLs on action. Feel free to contribute.

By the way, there are sonos plugins out there for homebridge ;-)

**Comment by suxus-zz** [comment]
Hello, thank you, but what is the idea behind the stateless switch, what kind of events can i trigger with this button?

I know, but my idea was that i can use this plugin (webhooks) for my sonos.

**Comment by benzman81** [comment]
This was contributed by community. I think you can now use this as trigger for scenes. If you call the url of the plugin to "push the button" homekit can react to it and do something.
For now, there wasnt the need to execute actions from a stateles switch. This addition would be a good enhancement.

**Comment by BetoRn** [comment]
@suxus-zz  Stateless switches are not supposed to work that way.

I’m using them to add a remote control to homekit, very much like a hue dimmer switch

...a Logitech harmony companion if you are curious

**Comment by jsiegenthaler** [comment]
Hi @benzman81: I agree with @suxus-zz. Stateless switches are a configuration ability for a physical remote control like the Philips Hue Dimmer Control. So you can only configure in Homekit, you cannot trigger any actions. Thus I believe this issue can be Closed as a non-issue
