### ISSUE TITLE
Add door sensor?

### ISSUE THREAD

**Issue by robertvorthman** [benzman81/homebridge-http-webhooks#5]
Great plugin.  I've got a motion sensor HomeKit trigger working great with my kitchen lights.  Could you please add door sensors?

More info here: https://github.com/KraigM/homebridge-wink/issues/42

**Comment by benzman81** [comment]
My understanding is that a contact sensor is the correct accessesory, just like how the elgatp eve door/window sensor is treated. Contact sensors are already supported. I use it myself for doors and windows. Now, with iOS 10.2 you even get notifications on state change is you like to.

**Comment by robertvorthman** [comment]
Awesome!  Thanks.  I read that the Eve sensors don't support notifications so I wasn't sure.

Are you able to automate triggering HomeKit scenes when you open a door?  That's what I am looking to do.

**Comment by benzman81** [comment]
Yes, Eve did not support it, but since 10.2 you can turn on Notifications in the Apple Home App. Until that it was only restricted to security releated devices like Door Locks. And yes, you can trigger a scene on contact closed or open.
