### ISSUE TITLE
Share thermostatscript.php missing file

### ISSUE THREAD

**Issue by lboue** [benzman81/homebridge-http-webhooks#50]
Hello,

Thanks for this wonderful plugin. I am testing the thermostat device and noticed the thermostatscript.php missing file.
Could you this thermostatscript.php that we can find in the Example config.json?

`                    "set_target_temperature_url": "http://127.0.0.1/thermostatscript.php?targettemperature=%f",        // %f is replaced by the target temperature`

Regards,

**Comment by benzman81** [comment]
@lboue this is just an example URL. You cann call any url there to communicate with your thermostat.

**Comment by lboue** [comment]
I understand. It was to avoid creating a script that already works. In my case I woud use a Xiaomi Aqara temperature sensor.

Regards,

**Comment by benzman81** [comment]
Ah ok. Since it was a community contribution by @iEns I do not have the script. Maybe you ask him.
