### ISSUE TITLE
airquality sensor status is 'undefined'

### ISSUE THREAD

**Issue by lboue** [benzman81/homebridge-http-webhooks#51]
Hello,

I have an issue with the airquality sensor. It is not recognized by homekit:

![img_1866](https://user-images.githubusercontent.com/938089/53372380-ff030400-3952-11e9-8fb2-a2b80955a836.jpg)

Here is the the config file:
```
{
    "platform": "HttpWebHooks",
    "webhook_port": "51828",
    "cache_directory": "./.node-persist/storage",
    "http_auth_user": "test",
    "http_auth_pass": "test",
    "sensors": [
        {
            "id": "sensor1",
            "name": "contact",
            "type": "contact"
        },
        {
            "id": "sensor2",
            "name": "airquality",
            "type": "airquality"
        }
    ]
}
```

Here is the homebridge log:
```
[2019-2-25 23:07:20] [HttpWebHooks] Getting current state for 'sensor2'...
[2019-2-25 23:07:20] [HttpWebHooks] State for 'sensor2' is 'undefined'
```

Could you help me to find the problem? 
Regards

**Comment by benzman81** [comment]
Sorry for long waiting time, been busy. The sensor for air quality works as expected. If you never set a value of set 0 as value the state will be undefined/unknown. You have to choose a value between 1 and 5.
