### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by mattfam0914** [benzman81/homebridge-http-webhooks#53]
Need a little assistance. I have homebridge up and running great. I am trying to send the webhooks however I am little confused where to add the config.json file. I already have one under ".homebridge" location. Do I need to update that config file with some of the examples and then add my IP address? I've tried to send some local webhooks but I don't get anything to happen. How does it know what specific device I am wanting to target (shade, light or whatever it may be)? 

Here is one of requests

http://192.XXX.X.X:port/?LivingShade=LivingShade&targetposition=80

I get nothing in return.

Any assistance would be great. Thanks!

**Comment by benzman81** [comment]
Hi,
you have always only one config file for a running homebridge instance. If you already have "platforms" defined in you config, then you just have to add the platform for this plugin and include any of the accessories you need (use the examples in the readme as template). Each accessory has an "id" in the config. So to update some state for a contact sensor you would have to call "http://yourHomebridgeServerIp:webhook_port/?accessoryId=theAccessoryIdOfTheContactSensor&state=true"

Hope that help.

Regards,
Markus

**Comment by benzman81** [comment]
Closed due to inactivity.
