### ISSUE TITLE
How to trigger a change to an existing accessory

### ISSUE THREAD

**Issue by vddgil** [benzman81/homebridge-http-webhooks#54]
Hello,

I use homebridge-knx, how can i use your plugin to handle light etc from my homebridgeknx ?

Thanks in advance,

Gil

**Comment by benzman81** [comment]
This plugin is able to probide accessories for homebridge that communicate via http. What do ou plan to do that homebridge knx doesnt?

**Comment by benzman81** [comment]
Closed due to inactivity.
