### ISSUE TITLE
Can't initialize accessory when using systemd 

### ISSUE THREAD

**Issue by tkmmobile** [benzman81/homebridge-http-webhooks#55]
Hi, guys. Can anyone help me for my situation? When I run out systemd command "homebridge.service", below error message has been always show up and never in-service state.

 4月 14 22:26:06 raspberrypi homebridge[7648]: [2019-4-14 22:26:06] [HttpWebHooks] Initializing HttpWebHooks platform...
 4月 14 22:26:06 raspberrypi homebridge[7648]: /home/pi/.nvm/versions/node/v10.15.0/lib/node_modules/homebridge-http-webhooks/node_modules/mkdirp/index.js:90

 4月 14 22:10:21 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
 4月 14 22:10:21 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
 4月 14 22:10:21 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.

But when I execute "homebridge" command instead systemctl, it doesn't happen. Note that my homebridge is installed other several plugin like philips-hue, broadlink, etc but it hasn't seen this kind of situation. 

below is my config.json
{
"platform": "HttpWebHooks",
"webhook_port": "51828",
 "pushbuttons": [
{
"id": "pushbutton1",
"name": "push_button1",
"push_url": "my URL", // (optional)
"push_method": "POST" // (optional)
}
]
}

FYI, I could see HttpWebHooks can initialize  my accessory when execution with homebridge command. 
[2019-4-14 22:08:36] [Philipshue] Initializing Hue platform...
[2019-4-14 22:08:36] [Philipshue] homebridge-hue v0.11.12, node v10.15.0, homebridge v0.4.46
[2019-4-14 22:08:36] [HttpWebHooks] Initializing HttpWebHooks platform...
[2019-4-14 22:08:36] [HttpWebHooks] Initializing platform accessory 'push_button1'...

**Comment by benzman81** [comment]
You should point the "cache_directory" to a directory the service user has permission to or give the user the required permission.

See benzman81/homebridge-nukiio#11

**Comment by benzman81** [comment]
Great
