### ISSUE TITLE
Light Intensity example

### ISSUE THREAD

**Issue by harryphm** [benzman81/homebridge-http-webhooks#56]
Hello !
Can you help posting a light intensity example in config? like a window covering please? I'm having some trouble with it !

Thanks !!
very useful plugin

**Comment by benzman81** [comment]
What exactly is the problem? Which accessesory are you using and what are you trying to do? Any log files?

**Comment by harryphm** [comment]
I'm using a diy arduino ac dimmer, I just need an example of usage... like the example of window cover... thanks !

**Comment by harryphm** [comment]
help please :(

**Comment by benzman81** [comment]
You can add a light sensor like this:

`{
                    "id": "sensor8",
                    "name": "Sensor name 8",
                    "type": "light"
}`

Setting light as for a dimmer is not supported yet.

**Comment by benzman81** [comment]
Light now supports brightness.
