### ISSUE TITLE
Homekit "spinning wheel" on status change

### ISSUE THREAD

**Issue by lpaso** [benzman81/homebridge-http-webhooks#57]
Hi.
First of all, thank you for your plugin, it's great !
I've got an issue with the garage door and security system accessories.
I configured one of each of them in my HomeBridge setup, and I'm using a custom RestAPI to command my garage door and security system.
Actions are OK (when I tap the garage button in HomeKit, the garage door opens and the security system takes the right state and goes in the right state when I choose the state in HomeKit), but the HomeKit button then has the "spinning wheel" indicating the action is still running indefinitely.
Does your plugin waits for a code returned to it for validating the status has changed ? Or a callback maybe ?
Thanks.

**Comment by benzman81** [comment]
fixed with 0.0.47

**Comment by lpaso** [comment]
Hi. That's OK for garage doors now, but security systems still does get the spinning Wheel for all status but disabled.

**Comment by benzman81** [comment]
fixed with 0.0.48
