### ISSUE TITLE
Permission error when running on docker

### ISSUE THREAD

**Issue by brunoamaral** [benzman81/homebridge-http-webhooks#61]
```
[9/1/2019, 9:16:26 PM] Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge/.node-persist'
```

This is fixed by using the proper volume path, `"cache_directory": "/homebridge/.node-persist",` for example.

Maybe it should be added to the documentation?

**Comment by benzman81** [comment]
Added information to documentation.
