### ISSUE TITLE
Issue with window covering

### ISSUE THREAD

**Issue by genfersee** [benzman81/homebridge-http-webhooks#62]
Hello all,

I have setup a window covering accessory as follow:
`
"id": "windowcovering1",
"name": "Store Bureau",
"open_url" : "http://myURL",
"open_method" : "GET",
"close_url" : "http://myURL",
"close_method" : "GET"
`

Via the Home app, when I tap on the blind icon to set the blind up, it works: the icon shows open and the physical blind goes up.

My issue is when I tap on the blind icon to set the blind down, it does not work as expected: the physical blind goes down, but the icon shows "closing" with a spining wheel running forever.

What am I doing wrong?

thanks in advance!

**Comment by benzman81** [comment]
this happens as HomeKit wanted to get a feedback from the roller shutter of current position using web hooks. I guess you did not use it this way. Thats why I added a new option "auto_set_current_position". Set it to true and it doesn't wait for feedback. Since version 0.1.7.
