### ISSUE TITLE
Permission denied - Newbie

### ISSUE THREAD

**Issue by AshleyMiller9696** [benzman81/homebridge-http-webhooks#63]
First of all - Thanks for the Plugin!

I wanted to setup a motion sensor

Config

{
"platform": "HttpWebHooks",
"webhook_port": "51828",
"sensors": [{
  "id": "sensor2",
  "name": "Eingang",
  "type": "motion",
  "cache_directory": "/var/homebridge/persist/",
  "autoRelease": true
 }]
}

Log
Getting current state for 'sensor2'... 
State for 'sensor2' is 'undefined'

But if I want to send a state http://192.168.178.80:51828/?accessoryId=sensor2&state=true

Error: EACCES: permission denied, open '/.node-persist/storage/6fa6149f73dba66bcb0cfbe76fde5a94'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at LocalStorage.persistKeySync (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/local-storage.js:460:16)
    at LocalStorage.setItemSync (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/local-storage.js:251:14)
    at HttpWebHooksPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-http-webhooks/index.js:415:34)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Got SIGTERM, shutting down Homebridge...

**Comment by benzman81** [comment]
See #15

**Comment by AshleyMiller9696** [comment]
For others:
The changing of the path didn't work (for me)

Had to give the user /etc/passwd root privileges

**Comment by dtrywets** [comment]
Problem occurs at my config too. I added the cache_directory and I also added root privileges to the homebridge user. 
any ideas?

**Comment by benzman81** [comment]
@dtrywets https://github.com/benzman81/homebridge-http-webhooks#cache-directory-storage-cache_directory

**Comment by dtrywets** [comment]
@benzman81 folder is drwxr-xr-x  2 homebridge root       4096 Mar 17 19:08 persist
as I deleted it manually to get the mkdir. it's writeable due to user homebridge beeing part of root-group or am I getting things wrong here?

**Comment by benzman81** [comment]
@dtrywets It looks like you choose the folder where homebridge persists its files. The folder ste as cache directory must be empty.

**Comment by dtrywets** [comment]
@benzman81 thanks.. I change to /var/homebridge/cache and it immediately stopped erroring. /persist was mentioned at smartapfel.de so I just kept it. 

now my devices aren't reacting at the home app, but I guess this is another thread. thanks a lot und schönen Abend :-)
