### ISSUE TITLE
Configurable Logging

### ISSUE THREAD

**Issue by rnilssoncx** [benzman81/homebridge-http-webhooks#64]
Can you provide an option to turn logging on and off for each webhook, or at least globally.  Right now some types log and some types have logging commented out (motion, for example).

**Comment by jsiegenthaler** [comment]
Hello @benzman81 : I absolutely love your work and use this plugin a lot but my homebridge gets flooded with logging. Can I help you clean up the logging? Maybe to different levels like .info and .debug?

**Comment by benzman81** [comment]
Of course, never thought about it. Pullrequests welcome.

**Comment by jsiegenthaler** [comment]
I'll get stuck in with some small Readme typo corrections

**Comment by jsiegenthaler** [comment]
OK, all get/set states have been moved to log.debug, which means the user can turn the logging on and off by using the native Homebridge Debug Mode -D
This will keep the Homebridge log much cleaner, and stop it flooding with the polling requests
I hope I didn't turn off too many log entries... I left the log entries in place for setting the state of a number of accessories.

**Comment by jsiegenthaler** [comment]
@benzman81 Hi Markus. Any chance of committing a release soo? My logs are getting flooded with Webhooks events and I'd like to bring my logs back to some form of normality ;)

**Comment by benzman81** [comment]
If you provide a pull request, I can look at it and merge it.

**Comment by jsiegenthaler** [comment]
Hi @benzman81  I did a pull request. It's my very first PR, so please check I did everything correctöy

**Comment by benzman81** [comment]
Merged pull request to reduce logging. If still too much, please open a new bug and name the belonging accessory.
