### ISSUE TITLE
Security status Disconnecting

### ISSUE THREAD

**Issue by miquellaboria** [benzman81/homebridge-http-webhooks#65]
When I activate the disarm order, plugin make the url call and it works well, but when home App ask the status always show disarming...:

<img width="285" alt="Captura de Pantalla 2019-11-05 a les 20 42 24" src="https://user-images.githubusercontent.com/1266767/68240231-cb619900-000c-11ea-8e04-2d4cc7611339.png">

If I check cache file:
{"key":"http-webhook-target-security-state-securitas","value":3}

Why on home App doesn't show disarmed?

**Comment by benzman81** [comment]
I cannot reproduce this. Could you try latest version and explain your steps to reproduce and maybe a log?

**Comment by miquellaboria** [comment]
The problem is when I change state via http call:

http://xxx.xxx.xxx.xxx:51828/?accessoryId=securitas&currentstate=1

I have service that check the alarm state and change it on the plugin.

**Comment by benzman81** [comment]
I think you also have to make a call with targetstate=1 or combine both parameters in one call.

**Comment by miquellaboria** [comment]
That works! Thank you!
