### ISSUE TITLE
Unable to find accessories ID

### ISSUE THREAD

**Issue by bxlouis** [benzman81/homebridge-http-webhooks#67]
Hi,

It might be a dumb question but I don't know how the hell I can find the homebridge accessories ID.
I do not see it anywhere in the documentation, nor on Google or nfarina's repo.

Could you please help me out?

Thanks.

**Comment by D-a-n-e** [comment]
I think this is the ID from config.json.

```
...
  "sensors": [
                    {
                    "id": "sensor1",    <-<-<-<-<-<-<-<-<-<-<-<-<- ID ?!
                    "name": "Sensor name 1",
                    "type": "contact"
                    },
...
```

**Comment by bxlouis** [comment]
Hi thanks for your answer. So it seems I did not understand the plugin purpose. Can you use it to trigger a device which does already exist in your configuration? Or can you only trigger the devices you create using the config file?

**Comment by D-a-n-e** [comment]
I don't know but I think it is only possible to handle devices from this plugin.
Can anybody confirm this?

**Comment by benzman81** [comment]
This is just for creating new accessesories with its own choosen ids.

**Comment by joshferrara** [comment]
Hi @benzman81  — Thanks so much for the great plugin!

I was wondering if you could help me understand if there is any way at all to use the webhook plugin to control existing homebridge accessories?

If not, could you explain the intended use for the plugin? 

Thanks so much!

**Comment by benzman81** [comment]
@joshferrara with this plugin you can create new devices in homekit. Those devices can trigger urls on their action, i.e. call an IFTTT or smarthome URL when turning a switch on. Additionally, this plugin starts a server that can receive calls to update the state of devices handles by this plugin,  i.e. a smarthome hub tells this plugin to change the switch state of the homekit device.

**Comment by joshferrara** [comment]
@benzman81 Ah! That makes total sense. Thank you for the explanation, I now have some great ideas about how to use this. Cheers!
