### ISSUE TITLE
HTTP Auth for push buttons

### ISSUE THREAD

**Issue by D-a-n-e** [benzman81/homebridge-http-webhooks#69]
Hello,

thanks for this great Plugin.
I use the push button to trigger a door opener. (Wemos D1 Mini with WebServer)

Is there an option for HTTP Auth in push buttons?

Best regards
Dane

**Comment by bxlouis** [comment]
Hi @D-a-n-e sorry to ask here but I need help and it seems you are successfully using the plugin. How did you find your accessory IDs in Homebridge?

**Comment by benzman81** [comment]
Not yet, feels free to provide a pull request.

**Comment by EddyK69** [comment]
Added push_body & push_header #66 were you can provide HTTP Authentication...

**Comment by benzman81** [comment]
Thanks @EddyK69
