### ISSUE TITLE
Honeywell T9 Thermostat

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [benzman81/homebridge-http-webhooks#70]
to get this connected to a device, what is everyone using. This plugin makes a webhook and then you send it to the device? or it connects to another service and then connects to that device?  Like is IFTTT being used?

**Comment by benzman81** [comment]
@d0n4v4nb3ck3r This plugin can call a http api of a device when a HomeKit device is triggered or receive http calls to change a HomeKit devices state. If Honeywell T9 Thermostat supports a web api, you can connect it. If it only supports IFTTT, then you could open a port to the web hook of this plugin and trigger it via IFTTT Maker Channel (web calls). But I would not recommend opening ports as this is a security issue an call are not encrypted see #68 .

**Comment by d0n4v4nb3ck3r** [comment]
So I have a developer account with Honeywell on https://developer.honeywellhome.com/api-methods?field_smart_method_tags_tid=39

From looking over this, I should be able to link this to your plugin? anyway you can help? are you on slack?

**Comment by benzman81** [comment]
No time for much support. But looks like it would work. Maybe you should try this first https://www.npmjs.com/package/homebridge-honeywell-home . Looks like this is what you want.

**Comment by d0n4v4nb3ck3r** [comment]
Ha I have tried that, doesn’t work

**Comment by benzman81** [comment]
@d0n4v4nb3ck3r well, if you set the http call correctly you should get it to work with this plugin.
