### ISSUE TITLE
Can's see webhooks accessory in Home app

### ISSUE THREAD

**Issue by zany92** [benzman81/homebridge-http-webhooks#71]
Hi,

I'm running HomeBridge on Raspbian with a default install, Config UI X and http-webhooks.
I added a single sensor but I can't see it in Home app.

When loading HomeBridge, all I get in the log is
`Loaded config.json with 0 accessories and 2 platforms.`

Here is my config file, did I missed something?
Thanks

{
    "bridge": {
        "name": "Homebridge",
        "username": "CB:22:3D:E2:CE:E2",
        "port": 51826,
        "pin": "033-44-033"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "sudo": true,
            "restart": "sudo -n systemctl restart homebridge"
        },
        {
            "platform": "HttpWebHooks",
            "webhook_port": "51828",
            "cache_directory": "/var/lib/homebridge/storage/",
            "http_auth_user": "test",
            "http_auth_pass": "test",
            "sensors": {
                "id": "sensor1",
                "name": "Sensor name 1",
                "type": "contact"
            }
        }
    ]
}

**Comment by benzman81** [comment]
Yes, you missed that sensors needs to be an array of objects in the json config. Compare it tobthe readme and you will see the differrence ;-)

**Comment by zany92** [comment]
Thank you, 🙏 
It was obvious but I did not saw the typo, very sorry.
