### ISSUE TITLE
invalid json returned - variable names should be strings

### ISSUE THREAD

**Issue by mshulman** [benzman81/homebridge-http-webhooks#74]
When setting a contact switch, I get this json body returned:
`{ success: true }`

but this doesn't parse as valid json. In other to be proper json, the variable name needs to be in quotes, like this:

`{ "success": true }`

**Comment by mshulman** [comment]
https://github.com/benzman81/homebridge-http-webhooks/pull/75

**Comment by benzman81** [comment]
Merged #75.
