### ISSUE TITLE
Need some help with the occupancy sensor 

### ISSUE THREAD

**Issue by alexbohariuc** [benzman81/homebridge-http-webhooks#78]
I configured an occupancy sensor to turn on/off my lights based on the following trigger:

- The wireless router detects I'm home > IFTTT sends a webhook request to homebridge sensor -> Home app turns on the lights based on the sensor

- The wireless router detects i left my home > IFTTT sends a webhook request to homebridge sensor 
 > Home app turns off the lights based on the sensor

Is there any way to setup a sensor that counts the number of people at home, in order to have the same setup on my wifes phone and turn off the lights when everyone left?

Thanks!

**Comment by benzman81** [comment]
Thats what homebridge-people is for ;-)
