### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Nastras** [benzman81/homebridge-http-webhooks#79]
Good morning Markus,

i have to report a bug, i noticed yesterday when i went to bed that after i updated to 0.0.55 no more webhook was working. Get this error when running it manually. After I'm down to 0.0.52 everything works again?

![F8AB3BD8-F195-464B-A433-C98D06A512C6](https://user-images.githubusercontent.com/27686185/72510915-8ea2f100-384a-11ea-8909-76ae89779b6a.jpeg)

![38F2B5B8-8C61-4238-9886-FFA0479FBB55](https://user-images.githubusercontent.com/27686185/72510930-9498d200-384a-11ea-9dad-a049251287ae.jpeg)

![IMG_34A1BCEC9847-1](https://user-images.githubusercontent.com/27686185/72510943-99f61c80-384a-11ea-91c3-914097d97329.jpeg)

**Comment by benzman81** [comment]
Version 0.0.56 should fix it. Please verify if it works now.

**Comment by Nastras** [comment]
Everything works again. Thanks!
