### ISSUE TITLE
Enhancement Request - Programmable Switch Event

### ISSUE THREAD

**Issue by jaquesp** [benzman81/homebridge-http-webhooks#8]
Would it be possible to implement a programmable switch event (as implemented within the following plugin: https://github.com/jourdant/homebridge-amazondash-ng) that switches on for a period and then automatically switches off? (i believe the default timeout is 15 seconds)?

**Comment by benzman81** [comment]
For now, my time is quite reduced on this. But feel free to make a contribution.

**Comment by benzman81** [comment]
In v0.0.24 I added switches that switch back to off after a second to simulate simple push buttons. If that helps you, feel free to close.
