### ISSUE TITLE
Thermostat body not working

### ISSUE THREAD

**Issue by sushenmathur** [benzman81/homebridge-http-webhooks#81]
Hi I am trying to send an IP address within the thermostat body, but its not working
here is my config 

`{
                    "id": "thermostat1",
                    "name": "Test AC",
                    "set_target_temperature_url": "http://localhost:3009/temp?targettemp=%f",
                    "set_target_temperature_method": "GET",
                    "set_target_temperature_body": "{ \"deviceIp\" : \"192.168.0.29\" }",
                    "set_target_temperature_headers": "{\"Content-Type\": \"application/json\"}",
                    "set_target_heating_cooling_state_url": "http://localhost:3009/state?targetstate=%b",
                    "set_target_heating_cooling_state_method": "GET",
                    "set_target_heating_cooling_state_body": "{\"deviceIp\" : \"192.168.0.29\" }",
                    "set_target_heating_cooling_state_headers": "{\"Content-Type\": \"application/json\"}"
                }`

**Comment by benzman81** [comment]
Could you clarify what is not working and append the log error?

**Comment by sushenmathur** [comment]
The body is not being sent with the GET request.
on parsing the body of the GET request at the nodejs app side the body is returning as undefined using homekit but when i do a GET request via postman i am able the parse the JSON body
![image](https://user-images.githubusercontent.com/21048866/73401692-5ebe1800-4337-11ea-88a7-832b1d3a58a0.png)
![image](https://user-images.githubusercontent.com/21048866/73401723-6978ad00-4337-11ea-8c30-8754485fa917.png)

**Comment by benzman81** [comment]
As stated in the readme, a body is only supported for GET and PUT.

**Comment by sushenmathur** [comment]
If you see the config file, the method is set to GET

**Comment by benzman81** [comment]
Sorry, meant POST and PUT, corrected it above, too.
