### ISSUE TITLE
Sensor contact always open

### ISSUE THREAD

**Issue by zany92** [benzman81/homebridge-http-webhooks#82]
![IMG_8ED424A2C5AE-1](https://user-images.githubusercontent.com/38879842/75192909-8006fe00-5755-11ea-8281-ad81daaba88a.jpeg)
Hi,

First of all, congratulation to the team, this is an amazing piece of work, thank you.

Everything works fine except for contact sensors. It always appears as "open" in Home App while other types are working well. Is it a bug or my json? Here is my test config for sensors. Can't figure out what could go wrong as it seems basic.

```
"sensors": [
                {
                    "id": "1",
                    "name": "1",
                    "type": "motion",
                    "autoRelease": true,
                    "autoReleaseTime": 2000
                },
                {
                    "id": "2",
                    "name": "2",
                    "type": "occupancy",
                    "autoRelease": true,
                    "autoReleaseTime": 2000
                },
                {
                    "id": "3",
                    "name": "3",
                    "type": "contact",
                    "autoRelease": true,
                    "autoReleaseTime": 2000
                }
            ]
```

**Comment by zany92** [comment]
Actually, I discovered that new sensors are not correctly initialized after they are created.
In the log, they appear as 
`State for '3' is 'undefined'`

After a first http query to initiate them at 'false', everything is fine.

**Comment by benzman81** [comment]
Currently on vacation. Will check in about three weeks.

**Comment by benzman81** [comment]
Fo my test contact sensor it is always closed by default. When activated/opened it closes automatically after timeout.

AdditionallyI don't get any "undefined" in the logs at all.

**Comment by zany92** [comment]
Really strange, I can't reproduce now on my side. Thank you anyway.
