### ISSUE TITLE
Temperature Sensor Issue

### ISSUE THREAD

**Issue by mmz06** [benzman81/homebridge-http-webhooks#85]
Hi,

First of all, thank you, and congratulation to the team, this solution is really ideal to make anything working with homebridge.

Everything works fine except for temperature sensors. 

            "sensors": [
                {
                    "id": "mysensor",
                    "name": "Temperature Piscine",
                    "type": "temperature"
                }
            ]

It seems the decimal value is being rounded instead of being sent properly:
When I send this request, https://XXXXX/?accessoryId=mysensor&value=18.6, the sensor is updated to 18.5, then when I try 18.7, it stays at 18.5, the, 18.8 it jumps to 19.0, then 18.9, it stays at 19.0.
Is this by design ? is it restricted from HomeKit app, or something due to homebridge or your plugin ?

Thank you for your help

**Comment by benzman81** [comment]
This is by design, but not for HomeKit, just for the Home App. If you use the Eve App, for example, it will show you the more detailed value.
