### ISSUE TITLE
[FEATURE] Eve App 4.2 Issue with homebridge-http-webhooks

### ISSUE THREAD

**Issue by DJay-X** [benzman81/homebridge-http-webhooks#86]
@benzman81 
The lates Eve for HomeKit App v4.2 is causing issues with several Homebridge Plugins.
They changed something so that the serial number of a device is linked somehow in the background. This was not with previous Eve versions.
Problems causing now like described here.
https://github.com/homebridge/homebridge/issues/2503
So all devices/switches etc. from homebridge-http-webhooks can't be sorted anymore and can't get an icon for each device separately. 

Do you see a solution to fix this "Eve" Issue, by changing something in your plugin?

Other plugin developers like @nicoduj homebridge-harmony already fixed the Eve Issue [#249](https://github.com/nicoduj/homebridge-harmony/issues/249).
@pponce with homebridge-script2 did a fix [#25](https://github.com/pponce/homebridge-script2/issues/25) by adding `"unique_serial":` which also was a great and working solution.

Thanks again for your work and the time you are investing generally.

**Comment by benzman81** [comment]
All accessories should now have a manufacturer, model and serial number using its id and type for uniqueness.

**Comment by DJay-X** [comment]
Looking absolutely good. 👍 
After installing the update and reboot Homebridge, the unique serial number for each device was showing in the Apple Home App.
Eve App however needed to be removed and downloaded again. After this the devices also showing their unique new serial number.
Individual sorting, assigning icon and placing and individual device to favorites does work now in Eve App, thanks to your work. 

Thanks a lot for this quick fix and the time you invested. 🙏
