### ISSUE TITLE
issue with thermostat and values 

### ISSUE THREAD

**Issue by alxalxnet** [benzman81/homebridge-http-webhooks#88]
If I tell Siri to set the target temperature of the Thermostat to a certain value, the value will be interpreted as Fahrenheit degrees (which is what I expect, since I have both homekit and homebridge set to Fahrenheit).

However, if I use the URL, the value is interpreted as Celsius and turned into Fahrenheit.

E.g.: In order to set the current temperature to 80°F I would use the following URL:
http://yourHomebridgeServerIp:webhook_port/?accessoryId=theAccessoryIdToUpdate&currenttemperature=80

However, the result is that the current temperature is set to... 176°F.

How do I specify that those 80 degrees are to be interpreted as Fahrenheit?

**Comment by benzman81** [comment]
@alxalxnet As of https://github.com/homebridge/HAP-NodeJS/blob/6ed0fffcbf99ebae94200356983f655bb9540775/src/lib/Characteristic.ts#L35 this plugin only supports celsius as input values.
