### ISSUE TITLE
IFTTT not working

### ISSUE THREAD

**Issue by poudenes** [benzman81/homebridge-http-webhooks#9]
Hi There,

Everything i try doen't work.

When i post this URL in browser : http://rpi.oudenes.photography:51828/?accessoryId=sensor4&state=true

it works, when i put this in a IFTTT request to send URL it doesn't show in my logs at all.

Can someone tell me what i do wrong?

Even locative doesnt work as well...

Port 51828 is forwarded to the Homebridge:

Public UDP Ports: 51828
Public TCP Ports: 51828
Private IP Address: x.x.x.x
Private UDP Ports: 51828
Private TCP Ports: 51828

**Comment by benzman81** [comment]
I had this once, too. Turned out to be a firewall problem as blocked ip's from a lot of countries, US included. In my case the IFTTT log showed that it got triggered but failed calling the address.

**Comment by poudenes** [comment]
Its now working with Locative. So thats ok.but would be nice when all trigger things will be in one app.
 :)

**Comment by benzman81** [comment]
Works with IFTTT for me, so must be some routing error.
