### ISSUE TITLE
Names of Stateless Switches?

### ISSUE THREAD

**Issue by mkrug1** [benzman81/homebridge-http-webhooks#91]
Hello,
This is a GREAT plug in for HomeBridge! I am using it for about a dozen items around my HomeKit.  Thanks for the support.

I am having an issue with naming 'Stateless Switches.' In my config (shown below) I have given names to all the switches, but on my phone they show up as "Button 1", "Button 2"... (see screen shot).
Is there a way to have the names in the config show up in HomeKit? 

Thank you for the consideration,
--MK 

![IMG_2631](https://user-images.githubusercontent.com/37394036/84207469-7349b400-aa7f-11ea-9ce2-9cfea4f83ac1.jpeg)

```
"statelessswitches": [
        {
            "id": "colorstatelessswitches",
            "name": "Color Buttons",
            "buttons": [
                {
                    "name": "Red",
                    "double_press": false,
                    "long_press": false
                },
                {
                    "name": "Blue",
                    "double_press": false,
                    "long_press": false
                },
                {
                    "name": "Green",
                    "double_press": false,
                    "long_press": false
                }
            ]
        }
    ]
```

**Comment by benzman81** [comment]
The name of the buttons do not appear in Home app but appear in Eve app. Nothing we can do about it. Added this hint to the "name" property in the readme.
