### ISSUE TITLE
Trigger change for boolean accessory does not work incase of switches, outlets but does work for contacts

### ISSUE THREAD

**Issue by umar14** [benzman81/homebridge-http-webhooks#93]
If I trigger a change in a switch, it will work for the first change and then if I change again homebridge crashes

**Comment by benzman81** [comment]
I cannot reproduce this. Could you try latest version and explain your steps to reproduce (i.e. what trigger means http or home app) and include the log from the crash?

**Comment by umar14** [comment]
I update to the latest version and it's working. Thanks!
