### ISSUE TITLE
Config UI X Support

### ISSUE THREAD

**Issue by donavanbecker** [benzman81/homebridge-http-webhooks#96]
Anyway you can add support for config ui x, like with pull request #94.

**Comment by benzman81** [comment]
Will have a look next time. Just did a huge restructuring.

**Comment by benzman81** [comment]
Why did you close this?

**Comment by donavanbecker** [comment]
Since we had the Pull Request. But I reopened it.

**Comment by donavanbecker** [comment]
@benzman81 any luck?

**Comment by benzman81** [comment]
Fixed by #94. Opened new issue #97
